# Generated by Django 5.2.9 on 2025-12-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base monthly price', max_digits=8),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('three_months', '3 Months (-10%)'), ('six_months', '6 Months (-20%)'), ('yearly', 'Yearly (-40%)')], default='monthly', max_length=20),
        ),
    ]
