# Generated by Django 5.2.9 on 2025-12-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_plan_price_plan_is_active_plan_monthly_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='number_of_staff',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
