# Generated by Django 5.2.9 on 2025-12-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_plan_number_of_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='number_of_staff',
            new_name='max_number_of_staff',
        ),
    ]
