# Generated by Django 4.2.27 on 2026-01-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_plan_created_at_plan_features_plan_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id_monthly',
            field=models.CharField(blank=True, help_text='Stripe Price ID for monthly', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id_six_months',
            field=models.CharField(blank=True, help_text='Stripe Price ID for 6 months', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id_three_months',
            field=models.CharField(blank=True, help_text='Stripe Price ID for 3 months', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id_yearly',
            field=models.CharField(blank=True, help_text='Stripe Price ID for yearly', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Stripe Product ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='Cancel subscription at period end'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due'), ('unpaid', 'Unpaid')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_latest_invoice_id',
            field=models.CharField(blank=True, help_text='Latest Stripe Invoice ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe Subscription ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripe_charge_id',
            field=models.CharField(blank=True, help_text='Stripe Charge ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, help_text='Stripe Invoice ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe Payment Intent ID', max_length=255, null=True),
        ),
    ]
