# Generated by Django 5.2.9 on 2026-01-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_plan_stripe_price_id_monthly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='additional_worker_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per additional worker per month', max_digits=8),
        ),
        migrations.AddField(
            model_name='plan',
            name='base_monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base monthly price for included workers', max_digits=8),
        ),
        migrations.AddField(
            model_name='plan',
            name='base_workers',
            field=models.PositiveIntegerField(default=3, help_text='Number of workers included in base price'),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_additional_worker_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID for additional workers', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='num_workers',
            field=models.PositiveIntegerField(default=3, help_text='Number of workers in this subscription'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_number_of_staff',
            field=models.PositiveIntegerField(default=3, help_text='Deprecated: use base_workers'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Deprecated: use base_monthly_price', max_digits=8),
        ),
        migrations.AlterField(
            model_name='plan',
            name='stripe_price_id_monthly',
            field=models.CharField(blank=True, help_text='Stripe Price ID for monthly base', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='stripe_price_id_six_months',
            field=models.CharField(blank=True, help_text='Stripe Price ID for 6 months base', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='stripe_price_id_three_months',
            field=models.CharField(blank=True, help_text='Stripe Price ID for 3 months base', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='stripe_price_id_yearly',
            field=models.CharField(blank=True, help_text='Stripe Price ID for yearly base', max_length=255, null=True),
        ),
    ]
