# Generated by Django 5.2.9 on 2026-01-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_plan_additional_worker_price_plan_base_monthly_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='trial_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of free trial days (0 = no trial)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_end',
            field=models.DateField(blank=True, help_text='End date of trial period', null=True),
        ),
    ]
