# Generated by Django 4.2.17 on 2026-01-19 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_plan_trial_days_subscription_trial_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='max_number_of_staff',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='monthly_price',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='stripe_additional_worker_price_id',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='stripe_price_id_monthly',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='stripe_price_id_six_months',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='stripe_price_id_three_months',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='stripe_price_id_yearly',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='stripe_product_id',
        ),
    ]
