# Generated by Django 4.2.17 on 2026-01-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_remove_plan_max_number_of_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='cancel_at_period_end',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_latest_invoice_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='stripe_charge_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='stripe_invoice_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='stripe_payment_intent_id',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='num_workers',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trial_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
