# Generated by Django 4.2.27 on 2026-01-21 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_company_description_alter_staff_specialization'),
        ('billing', '0011_transaction_stripe_invoice_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(help_text='Function where error occurred', max_length=255)),
                ('error_message', models.TextField(help_text='Stripe error message')),
                ('error_type', models.CharField(blank=True, help_text='Stripe error type (e.g., card_error)', max_length=100)),
                ('request_params', models.JSONField(blank=True, default=dict, help_text='What was being attempted')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
