# Generated by Django 4.2.17 on 2026-02-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_convert_descriptions_to_multilingual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.JSONField(blank=True, default=dict, help_text="Description by language: {'en': 'Description in English', 'es': 'Descripción en español', 'ca': 'Descripció en català'}"),
        ),
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text="Features by language: {'en': ['WhatsApp', 'Email'], 'es': ['WhatsApp', 'Correo electrónico'], 'ca': ['WhatsApp', 'Correu electrònic']}"),
        ),
    ]
