# Generated by Django 4.2.17 on 2026-02-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_alter_plan_description_alter_plan_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='whatsapp_included',
            field=models.BooleanField(default=False, help_text='Whether WhatsApp feature is included in this plan'),
        ),
    ]
