# Generated by Django 4.2.17 on 2026-02-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_plan_whatsapp_included'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('three_months', '3 Months (-10%)'), ('six_months', '6 Months (-15%)'), ('yearly', 'Yearly (-30%)')], default='monthly', max_length=20),
        ),
    ]
