# Generated by Django 4.2.17 on 2026-02-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_alter_subscription_billing_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('three_months', '3 Months'), ('six_months', '6 Months'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
    ]
