# Generated by Django 4.2.17 on 2026-05-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_alter_subscription_billing_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe Subscription ID', max_length=255, null=True),
        ),
    ]
