# Generated by Django 5.2.9 on 2025-12-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='companies.service'),
        ),
    ]
