# Generated by Django 5.2.9 on 2025-12-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='social_media',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
