# Generated by Django 5.2.9 on 2025-12-16 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_social_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='active',
            new_name='is_active',
        ),
    ]
