# Generated by Django 5.2.9 on 2025-12-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_rename_active_service_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='break_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='out_of_office',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='out_of_office_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='out_of_office_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
