# Generated by Django 5.2.9 on 2025-12-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_staff_break_end_staff_break_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('email_type', models.CharField(default='registration', max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_traceback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='companies_e_created_4b3442_idx'), models.Index(fields=['status', '-created_at'], name='companies_e_status_e967b1_idx'), models.Index(fields=['recipient_email'], name='companies_e_recipie_00dfed_idx')],
            },
        ),
    ]
