# Generated by Django 5.2.9 on 2026-01-03 15:14

import companies.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=companies.utils.company_img_upload),
        ),
        migrations.AlterField(
            model_name='companyimage',
            name='image',
            field=models.ImageField(upload_to=companies.utils.company_img_upload),
        ),
        migrations.AlterField(
            model_name='staff',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=companies.utils.company_img_upload),
        ),
    ]
