# Generated by Django 5.2.9 on 2026-01-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_company_logo_alter_companyimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='need_staff_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
