# Generated by Django 5.2.9 on 2026-01-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_service_need_staff_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
