# Generated by Django 4.2.17 on 2026-02-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_company_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='uuid',
        ),
    ]
