# Generated by Django 4.2.17 on 2026-02-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_remove_company_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='use_smart_booking',
            field=models.BooleanField(default=False),
        ),
    ]
