# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_remove_company_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='online_appointments_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
