# Generated by Django 4.2.17 on 2026-02-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_company_online_appointments_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='available_dates',
            field=models.JSONField(blank=True, default=list, help_text='List of dates when this service is available (format: YYYY-MM-DD). Max 10 dates.'),
        ),
    ]
