# Generated by Django 4.2.17 on 2026-02-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_add_service_available_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='restrict_to_available_dates',
            field=models.BooleanField(default=False, help_text='If checked, this service will only be available on the specified dates below'),
        ),
    ]
