# Generated by Django 4.2.17 on 2026-02-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_add_restrict_to_available_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='working_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
