# Generated by Django 4.2.17 on 2026-02-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_add_staff_working_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='time_for_servicing',
            field=models.PositiveIntegerField(default=0, help_text='Additional time for servicing after the appointment in minutes'),
        ),
    ]
