# Generated by Django 4.2.17 on 2026-03-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_service_time_for_servicing'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='calendar_step_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Calendar time slot interval in minutes (e.g., 15, 30, 60)'),
        ),
    ]
