# Generated by Django 4.2.17 on 2026-02-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_service_time_for_servicing'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='accepts_online_payments',
            field=models.BooleanField(default=False, help_text='Whether salon accepts online payments for bookings'),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connect Account ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_charges_enabled',
            field=models.BooleanField(default=False, help_text='Whether the account can receive payments'),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_details_submitted',
            field=models.BooleanField(default=False, help_text='Whether account details have been submitted'),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether Stripe onboarding is complete'),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_payouts_enabled',
            field=models.BooleanField(default=False, help_text='Whether the account can receive payouts'),
        ),
    ]
