# Generated by Django 4.2.17 on 2026-03-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_company_accepts_online_payments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='requires_online_payment',
            field=models.BooleanField(default=False, help_text='If checked, customers must pay online when booking this service'),
        ),
    ]
