# Generated by Django 4.2.17 on 2026-03-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_company_calendar_step_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='accepts_online_payments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_details_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_payouts_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
