# Generated by Django 4.2.17 on 2026-04-01 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_company_accepts_online_payments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_day_off', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_working_hours', to='companies.staff')),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('staff', 'day_of_week')},
            },
        ),
    ]
