# Generated by Django 4.2.17 on 2026-04-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_staffworkinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='out_of_office_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='out_of_office_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
