# Generated by Django 4.2.17 on 2026-04-21 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_change_out_of_office_to_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffOutOfOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(help_text='When the out-of-office period starts')),
                ('end_datetime', models.DateTimeField(help_text='When the out-of-office period ends')),
                ('reason', models.CharField(blank=True, help_text="Optional reason (e.g., 'Vacation', 'Sick leave')", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_of_office_periods', to='companies.staff')),
            ],
            options={
                'verbose_name': 'Staff Out of Office',
                'verbose_name_plural': 'Staff Out of Office Periods',
                'ordering': ['start_datetime'],
            },
        ),
    ]
