# Generated by Django 4.2.17 on 2026-04-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='whatsappconversation',
            new_name='whatsapp_bo_phone_n_8056eb_idx',
            old_name='whatsapp_bo_phone_n_idx',
        ),
    ]
