# Generated by Django 5.2.9 on 2025-12-10 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Cancelled')], default=0, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.staff')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.customer')),
            ],
        ),
    ]
