# Generated by Django 5.2.9 on 2025-12-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delete_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
