# Generated by Django 5.2.9 on 2025-12-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_delete_code'),
        ('companies', '0006_staff_break_end_staff_break_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='belongs_to_companies',
            field=models.ManyToManyField(related_name='customers', to='companies.company'),
        ),
    ]
