# Generated by Django 5.2.9 on 2025-12-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_customer_belongs_to_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='belongs_to_companies',
        ),
    ]
