# Generated by Django 5.2.9 on 2025-12-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_customer_belongs_to_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country_code',
            field=models.CharField(blank=True, choices=[('US', '🇺🇸 United States'), ('GB', '🇬🇧 United Kingdom'), ('CA', '🇨🇦 Canada'), ('AU', '🇦🇺 Australia'), ('NZ', '🇳🇿 New Zealand'), ('IE', '🇮🇪 Ireland'), ('DE', '🇩🇪 Germany'), ('FR', '🇫🇷 France'), ('ES', '🇪🇸 Spain'), ('IT', '🇮🇹 Italy'), ('NL', '🇳🇱 Netherlands'), ('BE', '🇧🇪 Belgium'), ('AT', '🇦🇹 Austria'), ('CH', '🇨🇭 Switzerland'), ('SE', '🇸🇪 Sweden'), ('NO', '🇳🇴 Norway'), ('DK', '🇩🇰 Denmark'), ('FI', '🇫🇮 Finland'), ('PL', '🇵🇱 Poland'), ('CZ', '🇨🇿 Czechia'), ('PT', '🇵🇹 Portugal'), ('GR', '🇬🇷 Greece'), ('HU', '🇭🇺 Hungary'), ('RO', '🇷🇴 Romania'), ('RU', '🇷🇺 Russia'), ('UA', '🇺🇦 Ukraine'), ('MX', '🇲🇽 Mexico'), ('BR', '🇧🇷 Brazil'), ('AR', '🇦🇷 Argentina'), ('CL', '🇨🇱 Chile'), ('CO', '🇨🇴 Colombia'), ('PE', '🇵🇪 Peru'), ('VE', '🇻🇪 Venezuela'), ('JP', '🇯🇵 Japan'), ('CN', '🇨🇳 China'), ('IN', '🇮🇳 India'), ('SG', '🇸🇬 Singapore'), ('KR', '🇰🇷 South Korea'), ('TH', '🇹🇭 Thailand'), ('MY', '🇲🇾 Malaysia'), ('PH', '🇵🇭 Philippines'), ('VN', '🇻🇳 Vietnam'), ('ID', '🇮🇩 Indonesia'), ('ZA', '🇿🇦 South Africa'), ('EG', '🇪🇬 Egypt'), ('NG', '🇳🇬 Nigeria'), ('KE', '🇰🇪 Kenya'), ('AE', '🇦🇪 United Arab Emirates'), ('SA', '🇸🇦 Saudi Arabia'), ('IL', '🇮🇱 Israel'), ('TR', '🇹🇷 Turkey'), ('NZ', '🇳🇿 New Zealand')], max_length=10, null=True),
        ),
    ]
