# Generated by Django 5.2.9 on 2026-01-04 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_customer_country_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes (set by staff if need_staff_confirmation)', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price (set by staff if need_staff_confirmation)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Cancelled'), (3, 'PreBooked')], default=0, max_length=20),
        ),
    ]
