# Generated by Django 4.2.17 on 2026-02-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_notes_booking_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_notes',
            field=models.TextField(blank=True, help_text='Notes added by the client when booking', null=True),
        ),
    ]
