# Generated by Django 4.2.17 on 2026-04-13 14:59

from django.db import migrations


def populate_booking_phone(apps, schema_editor):
    """Copy customer phone to booking_phone for existing bookings"""
    Booking = apps.get_model('bookings', 'Booking')
    
    # Update all bookings that don't have booking_phone set
    for booking in Booking.objects.filter(booking_phone__isnull=True):
        booking.booking_phone = booking.customer.phone
        booking.booking_country_code = booking.customer.country_code
        booking.save(update_fields=['booking_phone', 'booking_country_code'])


def reverse_populate(apps, schema_editor):
    """Reverse migration - clear booking_phone"""
    Booking = apps.get_model('bookings', 'Booking')
    Booking.objects.all().update(booking_phone=None, booking_country_code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_booking_country_code_booking_booking_phone'),
    ]

    operations = [
        migrations.RunPython(populate_booking_phone, reverse_populate),
    ]
