# Generated by Django 4.2.17 on 2026-04-13 15:03

from django.db import migrations
import re


def get_country_prefix(country_code, country_choices):
    """Get the phone prefix for a country code"""
    if not country_code:
        return ''
    
    if country_code.startswith('+'):
        return country_code
    
    for code, prefix in country_choices:
        if code == country_code:
            return prefix
    
    return ''


def normalize_phone_migration(phone, country_code, country_choices):
    """Normalize phone number to E.164 format"""
    if not phone:
        return phone
    
    # Remove whatsapp: prefix if present
    phone = phone.replace('whatsapp:', '').strip()
    
    # If phone already starts with +, just clean it
    if phone.startswith('+'):
        cleaned = '+' + re.sub(r'\D', '', phone[1:])
        return cleaned
    
    # Remove all non-digit characters
    digits_only = re.sub(r'\D', '', phone)
    
    # Remove leading zeros
    digits_only = digits_only.lstrip('0')
    
    if not digits_only:
        return phone
    
    # Get the country code prefix
    country_prefix = get_country_prefix(country_code, country_choices)
    
    # If we have a country prefix, combine it
    if country_prefix:
        return f"{country_prefix}{digits_only}"
    
    # If number looks like it has country code, just add +
    if len(digits_only) >= 10:
        return f"+{digits_only}"
    
    return phone


def normalize_existing_phones(apps, schema_editor):
    """Normalize all existing booking phone numbers"""
    Booking = apps.get_model('bookings', 'Booking')
    
    # Get COUNTRY_CHOICES - we need to define it here since we can't import from app
    # This is a simplified version with common countries
    COUNTRY_CHOICES = [
        ('ES', '+34'), ('FR', '+33'), ('IT', '+39'), ('DE', '+49'), ('GB', '+44'),
        ('US', '+1'), ('CA', '+1'), ('MX', '+52'), ('BR', '+55'), ('AR', '+54'),
        ('PT', '+351'), ('PL', '+48'), ('RO', '+40'), ('NL', '+31'), ('BE', '+32'),
        ('GR', '+30'), ('CZ', '+420'), ('HU', '+36'), ('SE', '+46'), ('NO', '+47'),
        ('DK', '+45'), ('FI', '+358'), ('IE', '+353'), ('AT', '+43'), ('CH', '+41'),
        ('UA', '+380'), ('RU', '+7'), ('TR', '+90'), ('IL', '+972'), ('SA', '+966'),
        ('AE', '+971'), ('IN', '+91'), ('CN', '+86'), ('JP', '+81'), ('KR', '+82'),
        ('AU', '+61'), ('NZ', '+64'), ('SG', '+65'), ('MY', '+60'), ('TH', '+66'),
        ('PH', '+63'), ('ID', '+62'), ('VN', '+84'), ('EG', '+20'), ('ZA', '+27'),
        ('NG', '+234'), ('KE', '+254'), ('MA', '+212'), ('TN', '+216'), ('DZ', '+213'),
        ('CL', '+56'), ('CO', '+57'), ('PE', '+51'), ('VE', '+58'), ('EC', '+593'),
        ('UY', '+598'), ('PY', '+595'), ('BO', '+591'), ('CR', '+506'), ('PA', '+507'),
        ('LV', '+371'), ('LT', '+370'), ('EE', '+372'), ('SK', '+421'), ('SI', '+386'),
        ('HR', '+385'), ('BG', '+359'), ('RS', '+381'), ('BA', '+387'), ('MK', '+389'),
    ]
    
    updated_count = 0
    for booking in Booking.objects.all():
        if booking.booking_phone:
            original = booking.booking_phone
            normalized = normalize_phone_migration(
                booking.booking_phone, 
                booking.booking_country_code,
                COUNTRY_CHOICES
            )
            if normalized != original:
                booking.booking_phone = normalized
                booking.save(update_fields=['booking_phone'])
                updated_count += 1
    
    print(f"Normalized {updated_count} booking phone numbers")


def reverse_normalize(apps, schema_editor):
    """Reverse is not safe - we can't un-normalize"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_populate_booking_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_existing_phones, reverse_normalize),
    ]
