# Generated by Django 4.2.17 on 2026-04-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_normalize_existing_booking_phones'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('en', 'English'), ('ru', 'Русский'), ('uk', 'Українська')], help_text="Customer's preferred language for communications", max_length=5, null=True),
        ),
    ]
