# Generated by Django 4.2.17 on 2026-04-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_customer_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_by',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('staff', 'Staff'), ('whatsapp', 'WhatsApp')], help_text="Indicates how the booking was created (e.g., 'client', 'staff', 'whatsapp')", max_length=60, null=True),
        ),
    ]
